name: Deploy to web

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependecies
      run: |
        python -m install pip --upgrade pip
        pip install flask pytest
    - name: Run Test
        pytest test_app.py
  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Simulate deployment
      run: |
        nohup python3 -m http.server 8000 &
